### PR TITLE
made some slight changes to allow sailboat to handle the perpendicula…

### PR DESCRIPTION
**Pull request by JoshuaJSam**
…r crossing edge case

### CODE REVIEW

**Comment by tylerlum** [comment]
image

Great work so far. From our discussion today, we will try to have code like:

for loop in main loop:
  for obstacle in obstacles:
    if obstacle on straight line path to waypoint:
        obstacle.doubleLength()

   regular pathfind.

**Comment by tylerlum** [comment]
This avoids problem of extending ALL boats, which could block viable paths

**Comment by tylerlum** [comment]
Future work: See if works okay with boats of different speeds (slow,med,fast), changing speeds (accelerate, decelerate), and turning (turn left, turn right)

**Comment by tylerlum** [comment]
```
    # Get setup parameters from state for ompl plan()
    # Convert all latlons to NE in km wrt referenceLatlon
    referenceLatlon = state.globalWaypoint
    start = utils.latlonToXY(state.position, referenceLatlon)
    goal = utils.latlonToXY(state.globalWaypoint, referenceLatlon)
    dimensions = getXYLimits(start, goal)
    obstacles = obs.getObstacles(state, referenceLatlon)

    '''Suggestd psuedocode
    startX = start[0]
    startY = start[1]
    goalX = start[0]
    startY = start[1]
    straight_line_points = []
    for i in 20:
        straight_line_points.append(i *(goalX - startX) + startX
    for point in straith_line_points:
        for obstacle in obstacles:
        if not obstacle.isValid(point):
            obstacle.length *= 2
    '''

```

In Path.py's createPath()

**Comment by tylerlum** [comment]
Another idea came to mind: we could also change our state space for pathfinding. Right now it is a 2D grid of real numbers, but maybe we can discretize the space. As long as the resolution isn't too low, it could significantly improve pathfinding speed and quality.

**Comment by tylerlum** [comment]
Works great right now, but only on PRMStar, not RRTStar. May change from https://ompl.kavrakilab.org/classompl_1_1base_1_1ValidStateSampler.html (ValidStateSampler) to https://ompl.kavrakilab.org/classompl_1_1base_1_1StateSampler.html (StateSampler).

**Comment by tylerlum** [comment]
Ideas:

- Add prints to sampler to see which x,y values are being sampled (could even store and plot these to visualize)
- Understand characteristics of the sampling (too dense in one region, sampling not enough, sampling too much, etc.)
- Iterate by improving the sampling algorithm based on above (eg. store set of sampled xy values and only sample points away from other points, sample on straight lines or on perpendicular lines, etc.)

**Comment by tylerlum** [comment]
image

Idea of solution: Not want the janky light green path, but the simple dark green path. Sampling at more regular intervals could fix this problem.

**Comment by JoshuaJSam** [comment]
image

Pushed newest changes to branch. Shown by the photo above, it's graphically shown that the state space is now represented by a set of equidistant points (nice clean diagonal lines) spanning from X high -> X low and from Y high -> Y low. This might be able to help the pathfinding algorithm because instead of sampling random points for the state space, there is more optimal diagonal paths between points. 

You can also increase the resolution of the state space by increasing the n variable in line 38 of updated_geometric_planner.py. It does seem to lag the program a lot though, n = 10 seems like the sweet spot.

**Comment by tylerlum** [comment]
Closing, as built on by #212

**Pull request closed without merging**
