### PR TITLE
Add real ships from MarineTraffic

### PR DESCRIPTION
**Pull request by haakov**
Poll MarineTraffic every 2 minutes for updated ship positions in the Juan de Fuca strait area.

The API key should expire some time during Tuesday (Feb 18).

### CODE REVIEW

**Comment by haakov** [comment]
The new API key is now live, it will work for 3 days.

**Comment by tylerlum** [comment]
Simon said we're getting access to AIS data in March :) will be great to use this at that time

**Comment by haakov** [comment]
Yeah! I suppose it will have to be handled differently, being a different service and all, but I believe we're already using pynmea (?) somewhere it shouldn't be too much work

**Comment by tylerlum** [comment]
Closing, as replaced by #225 and #192

**Pull request closed without merging**
