### PR TITLE
added launch argument to change number of mock AIS boats

### PR DESCRIPTION
**Pull request by JoshuaJSam**
Hmm, I made a mistake in the file commits and accidentally pushed my entire install folder :\   . During the meeting If someone can help me with git, can you show me how I fix this other than making a new branch from master and re-adding my changes there?  Also can you explain what the circleci lint failure means? Otherwise the launch argument has been added and is working as expected.

### CODE REVIEW

**Comment by tylerlum** [comment]
Awesome! Haha yeah Patrick had the same issue before

**Comment by tylerlum** [comment]
I believe you can do something like `git rm -r --cached install/castxml`
then `git status` should show that it was removed
then `git commit -m "Remove extra files"` that change
I think that's it, `git push` and see if it was removed on the PR

**Comment by tylerlum** [comment]
Lint makes sure you follow good coding style. I believe it failed because in the `install` folder, there are some poorly formatted Python files. Those will be gone when you remove the files

**Comment by JoshuaJSam** [comment]
@tylerlum It's working! Got it to do both `roslaunch local_pathfinding all.launch num_ais_ships:=0` and `roslaunch local_pathfinding all.launch num_ais_ships:=50` and saw the correct result. Defaults to 5 when no parameter is given.

**Comment by tylerlum** [comment]
Awesome! Great work, looks good to me!

**Review by tylerlum — APPROVED** [review]

**Comment by tylerlum** [comment]
Feel free to merge! :)

**Pull request merged**
