### PR TITLE
Move msgs to other repo

### PR DESCRIPTION
**Pull request by tylerlum**
The purpose of this pull request is to remove the `msg` folder and replace the use of `local_pathfinding.msg` with `sailbot_msg.msg`. It also updates the installation instructions to include the cloning of the `sailbot-msg` repository to still get this working. It also needs to update circleci to clone the sailbot-msg repository to add this dependency.

Addresses #119 and #149 

NOTE: To test this, please `cd` to your `catkin_ws/src` (should be able to see local_pathfinding when you write `ls`). Then `git clone https://github.com/UBCSailbot/sailbot-msg.git`. This adds in the msg files. THEN `cd ..` (so you'll be in `catkin_ws`) `catkin_make` `source devel/setup.bash`.

Then you can test with the usual `roslaunch local_pathfinding all.launch`

### CODE REVIEW

**Review by patrick-5546 — CHANGES_REQUESTED** [review]
When I try to run it on my computer, it seems like it cannot find the module `sailbot_msg.msg`. I have attached my terminal output below.

[Error MoveMsgsToOtherRepo1.txt](https://github.com/UBCSailbot/local-pathfinding/files/5497314/Error.MoveMsgsToOtherRepo1.txt)

**Comment by tylerlum** [comment]
Thanks for letting me know. Just added some info to the description. Could you try it again with those instructions and let me know if you run into any problems?

**Comment by JoshuaJSam** [comment]
@tylerlum I had the same issue as Patrick when I tried it earlier. Still getting an error even after following the info in the description and cloning the sailbot msg from git.
[errormsg.txt](https://github.com/UBCSailbot/local-pathfinding/files/5497483/errormsg.txt)

**Comment by tylerlum** [comment]
Thanks for letting me know guys. I just looked into this more and I missed a step. Just added to the description. Good that we have exact instructions to get this working now :)

**Review by patrick-5546 — APPROVED** [review]
Thanks for adding the instructions, I wouldn't have known how to get it working otherwise. Everything seems like its running properly on my computer now.

**Pull request merged**
