### PR TITLE
Debug waypoint reached

### PR DESCRIPTION
**Pull request by tylerlum**
Investigating bug with waypoint reached line and removepastwaypoints

### CODE REVIEW

**Comment by tylerlum** [comment]
@patrick-5546  fixed the issue with the waypoint reached line, so it is always the correct distance away.

TODO: Change behavior to probably never prepend boat position (do we need to do this in the case with lengthAfter==1)?

**Comment by tylerlum** [comment]
Fixed 2 issues:
1. Waypoint reached line in wrong position. Fixed by changing sin to cos
2. Boat still kind of goes "backwards" at times, so we improve the removePastWaypoints function. Only potential issue: with high speedup, boat will overshoot the waypoint, so this will make the boat skip a waypoint. Not a big deal, but good to note.

**Comment by tylerlum** [comment]
Ready for review.

**Review by patrick-5546 — APPROVED** [review]
Efficiently resolves the documented bug, glad this is working as expected now.

**Pull request merged**
